[default]
description = "Default permissions for Audion"
permissions = [
    "scan_music",
    "add_folder",
    "rescan_music",
    "get_default_music_dirs",
    "get_library",
    "get_tracks_paginated",
    "get_albums_paginated",
    "search_library",
    "get_tracks_by_album",
    "get_tracks_by_artist",
    "get_album",
    "get_albums_by_artist",
    "add_external_track",
    "delete_track",
    "delete_album",
    "reset_database",
    "sync_cover_paths_from_files",
    "migrate_covers_to_files",
    "get_track_cover_path",
    "get_batch_cover_paths",
    "get_album_art_path",
    "get_cover_as_asset_url",
    "preload_covers",
    "cleanup_orphaned_cover_files",
    "clear_base64_covers",
    "merge_duplicate_covers",
    "create_playlist",
    "get_playlists",
    "get_playlist_tracks",
    "add_track_to_playlist",
    "remove_track_from_playlist",
    "delete_playlist",
    "rename_playlist",
    "update_playlist_cover",
    "reorder_playlist_tracks",
    "like_track",
    "unlike_track",
    "is_track_liked",
    "get_liked_track_ids",
    "get_liked_tracks",
    "record_play",
    "get_top_tracks",
    "get_top_albums",
    "get_recently_played",
    "save_lrc_file",
    "load_lrc_file",
    "delete_lrc_file",
    "musixmatch_request",
    "get_lyrics",
    "get_current_lyric",
    "download_and_save_audio",
    "update_track_after_download",
    "update_local_src",
    "update_track_cover_url",
    "list_plugins",
    "install_plugin",
    "uninstall_plugin",
    "enable_plugin",
    "disable_plugin",
    "get_plugin_permissions",
    "grant_permissions",
    "check_cross_plugin_permission",
    "get_cross_plugin_permissions",
    "revoke_permissions",
    "get_plugin_dir",
    "check_plugin_updates",
    "update_plugin",
    "save_notification_image",
    "plugin_save_data",
    "plugin_get_data",
    "plugin_list_keys",
    "plugin_clear_data",
    "proxy_fetch",
    "get_window_start_mode",
    "set_window_start_mode",
    "audio_play",
    "audio_pause",
    "audio_resume",
    "audio_stop",
    "audio_set_volume",
    "audio_seek",
    "audio_get_state",
    "audio_is_finished",
    "audio_set_eq",
    "native_audio_available"
]
